#if !canImport(ObjectiveC)
import XCTest

extension FunctionBuilderExampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionBuilderExampleTests = [
        ("testDo", testDo),
        ("testIf", testIf),
        ("testIfElse", testIfElse),
        ("testMultipleLines", testMultipleLines),
        ("testSingleLines", testSingleLines),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FunctionBuilderExampleTests.__allTests__FunctionBuilderExampleTests),
    ]
}
#endif
