name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Swift
        run: |
          DEBIAN_FRONTEND=noninteractive
          SWIFT_DOWNLOAD_URL=https://swift.org/builds/swift-5.1-release/ubuntu1804/swift-5.1-RELEASE/swift-5.1-RELEASE-ubuntu18.04.tar.gz

          sudo --preserve-env apt-get install clang libicu-dev

          wget -qO - $SWIFT_DOWNLOAD_URL | sudo tar xvzf - -C / --strip 1

      - name: Run Tests
        run: swift test -c release
