name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Swift
        run: |

          sudo apt-get install clang libicu-dev


          wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
          gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift

          SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2019-09-04-a
          wget https://swift.org/builds/development/ubuntu1804/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu18.04.tar.gz
          tar xzf $SWIFT_VERSION-ubuntu18.04.tar.gz
          ls
