name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Swift
        run: |
          DEBIAN_FRONTEND=noninteractive
          SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2019-09-04-a
          SWIFT_DOWNLOAD_URL=https://swift.org/builds/development/ubuntu1804/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu18.04.tar.gz

          sudo --preserve-env apt-get install clang libicu-dev

          wget -qO - $SWIFT_DOWNLOAD_URL | sudo tar xvzf - -C / --strip 1

      - name: Run Tests
        run: swift test -c release
